// Magyar interjú gyakorlás — practice app. Pure browser, no backend.
// Data comes from data.js (window.HUNGARIAN_DATA), generated by extract.js.

const DATA = window.HUNGARIAN_DATA || [];
// Stable 1-based question number = position in the full list (the table order).
DATA.forEach((r, i) => { r.n = i + 1; });

// "Needs help" marks, persisted in the browser (no backend). Keyed by question
// text so marks survive data regeneration / reordering.
const MARK_KEY = "hu-marked";
const keyOf = (row) => row.hu_q;
let marked = new Set();
try { marked = new Set(JSON.parse(localStorage.getItem(MARK_KEY) || "[]")); } catch (e) { /* ignore */ }
function saveMarks() {
  try { localStorage.setItem(MARK_KEY, JSON.stringify([...marked])); } catch (e) { /* ignore */ }
}
const isMarked = (row) => marked.has(keyOf(row));
const markedCount = () => DATA.filter(isMarked).length;

const el = (id) => document.getElementById(id);
const ui = {
  category: el("category"), rate: el("rate"), rateLabel: el("rateLabel"),
  voice: el("voice"), hideText: el("hideText"), varyOpenings: el("varyOpenings"),
  autoplay: el("autoplay"), autoInterval: el("autoInterval"), autoLabel: el("autoLabel"),
  autoReadAnswer: el("autoReadAnswer"), autoOptions: el("autoOptions"),
  rangeFrom: el("rangeFrom"), rangeTo: el("rangeTo"), rangeReset: el("rangeReset"),
  rangeLabel: el("rangeLabel"), qnum: el("qnum"),
  empty: el("empty"), body: el("body"), voiceWarning: el("voiceWarning"),
  huQ: el("huQ"), enQ: el("enQ"), huA: el("huA"), enA: el("enA"),
  speakQ: el("speakQ"), speakA: el("speakA"), markBtn: el("markBtn"),
  revealButtons: el("revealButtons"), play: el("play"), progress: el("progress"),
};

let current = null;       // the active row + chosen phrasing
let queue = [];           // shuffled indices into the filtered set, consumed for no-repeat
let filtered = DATA;      // rows matching the current category
let huVoices = [];        // available hu-HU voices

// "Vary openings": ~1/3 of the time, preface the question with a softer open
// prompt built from the card's topic (in the -ról/-ről "about …" case).
const pickRand = (a) => a[Math.floor(Math.random() * a.length)];
const OPENING_CHANCE = 0.35;
const OPENINGS = [
  (t) => `Meséljen ${t}.`,                 // Tell me about …
  (t) => `Beszéljen ${t}.`,                // Talk about …
  (t) => `Mondjon valamit ${t}.`,          // Say something about …
  (t) => `Kérem, beszéljen ${t}.`,         // Please talk about …
  (t) => `Kérem, mondja el, mit tud ${t}.`,// Please tell me what you know about …
];
const CATEGORY_TOPICS = {
  "Personal details": "magáról",
  "Family": "a családjáról",
  "Ancestry & origin": "a származásáról",
  "Language learning": "a magyartanulásáról",
  "Education & work": "a munkájáról",
  "Home & residence": "az otthonáról",
  "Hobbies & free time": "a szabadidejéről",
  "Daily life & food": "a mindennapjairól",
  "Culture & history": "a magyar kultúráról",
  "Documents & application": "a dokumentumairól",
  "Motivation & future": "a terveiről",
  "Visiting Hungary": "a magyarországi látogatásáról",
  "General": "magáról",
  // Greeting/closing, small talk, interview procedure: no natural "about …" topic.
};

// ---- Speech ---------------------------------------------------------------
const synth = window.speechSynthesis;

function loadVoices() {
  const all = synth ? synth.getVoices() : [];
  huVoices = all.filter((v) => /^hu(-|_|$)/i.test(v.lang));
  ui.voice.innerHTML = "";
  if (huVoices.length === 0) {
    ui.voice.innerHTML = "<option>No Hungarian voice found</option>";
    ui.voice.disabled = true;
    ui.voiceWarning.textContent =
      "⚠ No Hungarian (hu-HU) voice detected. In Microsoft Edge they load automatically when online. " +
      "In Chrome, install a Hungarian language pack in Windows Settings → Time & language → Language.";
  } else {
    ui.voice.disabled = false;
    ui.voiceWarning.textContent = "";
    huVoices.forEach((v, i) => {
      const o = document.createElement("option");
      o.value = i;
      o.textContent = `${v.name}${v.localService ? "" : " (online)"}`;
      ui.voice.appendChild(o);
    });
  }
}

// Speak one or more Hungarian texts in order; onDone fires after the last one
// (or immediately if there's no voice, so autoplay can still advance on a timer).
function speakSequence(texts, onDone) {
  const list = texts.filter(Boolean);
  if (!synth || huVoices.length === 0 || list.length === 0) {
    if (onDone) onDone();
    return;
  }
  synth.cancel();
  list.forEach((text, i) => {
    const u = new SpeechSynthesisUtterance(text.replace(/\n/g, ". "));
    u.voice = huVoices[ui.voice.value] || huVoices[0];
    u.lang = u.voice.lang;
    u.rate = parseFloat(ui.rate.value);
    if (i === list.length - 1 && onDone) u.onend = onDone;
    synth.speak(u);
  });
}

function speak(text) { speakSequence([text]); }

// ---- Category + queue -----------------------------------------------------
function buildCategories() {
  const cats = [...new Set(DATA.map((r) => r.category))].sort();
  ui.category.innerHTML =
    `<option value="__all">All topics (${DATA.length})</option>` +
    `<option value="__marked">★ Needs help (${markedCount()})</option>`;
  cats.forEach((c) => {
    const n = DATA.filter((r) => r.category === c).length;
    const o = document.createElement("option");
    o.value = c;
    o.textContent = `${c} (${n})`;
    ui.category.appendChild(o);
  });
}

// Keep the "Needs help" option's count fresh without rebuilding the dropdown.
function refreshMarkedOption() {
  const opt = [...ui.category.options].find((o) => o.value === "__marked");
  if (opt) opt.textContent = `★ Needs help (${markedCount()})`;
}

// The range uses the absolute table number, so "30–50" means the same
// regardless of topic.
function computeRange() {
  let from = parseInt(ui.rangeFrom.value, 10);
  let to = parseInt(ui.rangeTo.value, 10);
  if (!Number.isFinite(from)) from = 1;
  if (!Number.isFinite(to)) to = DATA.length;
  from = Math.max(1, Math.min(from, DATA.length));
  to = Math.max(1, Math.min(to, DATA.length));
  if (from > to) [from, to] = [to, from];
  return { from, to };
}

// Rebuild the active set and force a fresh shuffle. Called on EVERY range/topic
// change (including each keystroke) so the next pick is always re-randomised.
function rebuildFiltered() {
  const { from, to } = computeRange();
  const c = ui.category.value;
  filtered = DATA.filter((r) => {
    if (r.n < from || r.n > to) return false;
    if (c === "__marked") return isMarked(r);
    return c === "__all" || r.category === c;
  });
  queue = [];                              // discard old order -> reshuffle next pick
}

// Commit version: also normalises the input boxes + label (runs on blur/reset).
function applyFilters() {
  const { from, to } = computeRange();
  ui.rangeFrom.value = from;
  ui.rangeTo.value = to;
  ui.rangeLabel.textContent = from === 1 && to === DATA.length ? "(all)" : `(#${from}–${to})`;
  rebuildFiltered();
}

// Build a shuffled, no-repeat play order. After a plain Fisher–Yates shuffle we
// de-cluster: siblings split from the same source cell (same .group) shouldn't
// land next to each other, otherwise reworded duplicates feel "un-random".
function buildQueue() {
  queue = filtered.map((_, i) => i);
  for (let i = queue.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [queue[i], queue[j]] = [queue[j], queue[i]];
  }
  const grp = (qi) => filtered[qi].group;
  for (let i = 1; i < queue.length; i++) {
    if (grp(queue[i]) !== grp(queue[i - 1])) continue;
    // pull in a later card from a different group (and not matching the next one)
    for (let j = i + 1; j < queue.length; j++) {
      if (grp(queue[j]) === grp(queue[i - 1])) continue;
      if (i + 1 < queue.length && grp(queue[j]) === grp(queue[i + 1])) continue;
      [queue[i], queue[j]] = [queue[j], queue[i]];
      break;
    }
  }
}

function nextRow() {
  if (queue.length === 0) buildQueue();
  return filtered[queue.pop()];
}

// ---- Render ---------------------------------------------------------------
function resetReveals() {
  [ui.enQ, ui.huA, ui.enA].forEach((node) => { node.hidden = true; });
  ui.speakA.hidden = true;
  [...ui.revealButtons.children].forEach((b) => b.classList.remove("active"));
}

// ---- Autoplay -------------------------------------------------------------
let autoTimer = null;
let playToken = 0;            // guards against stale speech-end callbacks

function clearAuto() {
  if (autoTimer) { clearTimeout(autoTimer); autoTimer = null; }
}

function scheduleNext(token) {
  clearAuto();
  if (!ui.autoplay.checked || token !== playToken) return;
  const secs = parseInt(ui.autoInterval.value, 10) || 10;
  autoTimer = setTimeout(() => { if (ui.autoplay.checked) play(); }, secs * 1000);
}

function play() {
  clearAuto();
  if (filtered.length === 0) {
    ui.body.classList.add("hidden");
    ui.empty.classList.remove("hidden");
    ui.empty.innerHTML = "<p>No questions match this topic and range. Widen the range or pick another topic.</p>";
    ui.progress.textContent = "";
    return;
  }
  const row = nextRow();
  if (!row) return;
  let phrasing = row.hu_q;
  const topic = CATEGORY_TOPICS[row.category];
  if (ui.varyOpenings.checked && topic && Math.random() < OPENING_CHANCE) {
    phrasing = `${pickRand(OPENINGS)(topic)} ${phrasing}`;
  }
  current = { row, phrasing };

  ui.empty.classList.add("hidden");
  ui.body.classList.remove("hidden");

  resetReveals();
  updateMarkButton();
  ui.qnum.textContent = `#${row.n}`;
  ui.huQ.textContent = phrasing;
  ui.huQ.hidden = ui.hideText.checked;       // interview mode: audio only first
  ui.enQ.textContent = row.en_q;
  ui.huA.textContent = row.hu_a;
  ui.enA.textContent = row.en_a;

  // Autoplay reading Q+A also reveals the answer so you can read along.
  const readAnswer = ui.autoplay.checked && ui.autoReadAnswer.checked && row.hu_a;
  if (readAnswer) { ui.huQ.hidden = false; ui.huA.hidden = false; ui.speakA.hidden = false; }

  const token = ++playToken;
  speakSequence(readAnswer ? [phrasing, row.hu_a] : [phrasing], () => scheduleNext(token));

  ui.progress.textContent =
    `${filtered.length - queue.length} / ${filtered.length} in “${ui.category.options[ui.category.selectedIndex].textContent}”`;
}

// ---- Needs-help marks -----------------------------------------------------
function updateMarkButton() {
  const on = current && isMarked(current.row);
  ui.markBtn.textContent = on ? "★" : "☆";
  ui.markBtn.classList.toggle("on", !!on);
}

function toggleMark() {
  if (!current) return;
  const k = keyOf(current.row);
  if (marked.has(k)) marked.delete(k); else marked.add(k);
  saveMarks();
  updateMarkButton();
  refreshMarkedOption();
  if (ui.category.value === "__marked") rebuildFiltered();  // keep marked-only set current
}

function toggleReveal(targetId, btn) {
  const node = el(targetId);
  const show = node.hidden;                    // hidden now -> reveal; visible -> hide again
  node.hidden = !show;
  if (btn) btn.classList.toggle("active", show);
  if (targetId === "huA") {
    ui.speakA.hidden = !show;
    if (show) {
      ui.huQ.hidden = false;                   // revealing the answer also shows the question
      speak(current.row.hu_a);
    } else if (synth) {
      synth.cancel();                          // hiding the answer stops it speaking
    }
  }
}

// ---- Wire up --------------------------------------------------------------
ui.play.addEventListener("click", play);
ui.speakQ.addEventListener("click", () => current && speak(current.phrasing));
ui.speakA.addEventListener("click", () => current && speak(current.row.hu_a));
ui.markBtn.addEventListener("click", toggleMark);

ui.revealButtons.addEventListener("click", (e) => {
  const btn = e.target.closest("button");
  if (!btn || !current) return;
  toggleReveal(btn.dataset.target, btn);
});

ui.rate.addEventListener("input", () => { ui.rateLabel.textContent = `${parseFloat(ui.rate.value).toFixed(2)}×`; });
ui.category.addEventListener("change", applyFilters);
// `input` = recompute immediately as they type (no stale queue); `change` =
// normalise the boxes on commit. Either way the queue is reset -> reshuffled.
ui.rangeFrom.addEventListener("input", rebuildFiltered);
ui.rangeTo.addEventListener("input", rebuildFiltered);
ui.rangeFrom.addEventListener("change", applyFilters);
ui.rangeTo.addEventListener("change", applyFilters);
ui.rangeReset.addEventListener("click", () => {
  ui.rangeFrom.value = 1;
  ui.rangeTo.value = DATA.length;
  applyFilters();
});
ui.hideText.addEventListener("change", () => { if (current) ui.huQ.hidden = ui.hideText.checked; });

// Autoplay
function refreshAutoUI() {
  ui.autoLabel.textContent = `${ui.autoInterval.value}s`;
  ui.autoOptions.classList.toggle("disabled", !ui.autoplay.checked);
}
ui.autoInterval.addEventListener("input", refreshAutoUI);
ui.autoplay.addEventListener("change", () => {
  refreshAutoUI();
  if (ui.autoplay.checked) {
    play();                                  // start the loop right away
  } else {
    clearAuto();
    playToken++;                             // invalidate any pending speech-end callback
    if (synth) synth.cancel();
  }
});

// Keyboard: Space/Enter = next, R = replay question.
document.addEventListener("keydown", (e) => {
  if (e.target.tagName === "SELECT" || e.target.tagName === "INPUT") return;
  if (e.code === "Space" || e.code === "Enter") { e.preventDefault(); play(); }
  else if (e.key.toLowerCase() === "r" && current) speak(current.phrasing);
  else if (e.key.toLowerCase() === "m") toggleMark();
});

if (synth) {
  loadVoices();
  synth.addEventListener("voiceschanged", loadVoices);
}
buildCategories();
ui.rangeFrom.max = DATA.length;
ui.rangeTo.max = DATA.length;
ui.rangeTo.value = DATA.length;
applyFilters();
ui.rateLabel.textContent = `${parseFloat(ui.rate.value).toFixed(2)}×`;
refreshAutoUI();
if (DATA.length === 0) ui.empty.innerHTML = "<p>⚠ No data loaded. Run <code>node extract.js</code> first.</p>";
