// Magyar interjú gyakorlás — practice app. Pure browser, no backend.
// Data comes from data.js (window.HUNGARIAN_DATA), generated by extract.js.

const DATA = window.HUNGARIAN_DATA || [];
// Stable 1-based question number = position in the full list (the table order).
DATA.forEach((r, i) => { r.n = i + 1; });

const el = (id) => document.getElementById(id);
const ui = {
  category: el("category"), rate: el("rate"), rateLabel: el("rateLabel"),
  voice: el("voice"), hideText: el("hideText"), varyOpenings: el("varyOpenings"),
  rangeFrom: el("rangeFrom"), rangeTo: el("rangeTo"), rangeReset: el("rangeReset"),
  rangeLabel: el("rangeLabel"), qnum: el("qnum"),
  empty: el("empty"), body: el("body"), voiceWarning: el("voiceWarning"),
  huQ: el("huQ"), enQ: el("enQ"), huA: el("huA"), enA: el("enA"),
  speakQ: el("speakQ"), speakA: el("speakA"),
  revealButtons: el("revealButtons"), play: el("play"), progress: el("progress"),
};

let current = null;       // the active row + chosen phrasing
let queue = [];           // shuffled indices into the filtered set, consumed for no-repeat
let filtered = DATA;      // rows matching the current category
let huVoices = [];        // available hu-HU voices

// "Vary openings": ~1/3 of the time, preface the question with a softer open
// prompt built from the card's topic (in the -ról/-ről "about …" case).
const pickRand = (a) => a[Math.floor(Math.random() * a.length)];
const OPENING_CHANCE = 0.35;
const OPENINGS = [
  (t) => `Meséljen ${t}.`,                 // Tell me about …
  (t) => `Beszéljen ${t}.`,                // Talk about …
  (t) => `Mondjon valamit ${t}.`,          // Say something about …
  (t) => `Kérem, beszéljen ${t}.`,         // Please talk about …
  (t) => `Kérem, mondja el, mit tud ${t}.`,// Please tell me what you know about …
];
const CATEGORY_TOPICS = {
  "Personal details": "magáról",
  "Family": "a családjáról",
  "Ancestry & origin": "a származásáról",
  "Language learning": "a magyartanulásáról",
  "Education & work": "a munkájáról",
  "Home & residence": "az otthonáról",
  "Hobbies & free time": "a szabadidejéről",
  "Daily life & food": "a mindennapjairól",
  "Culture & history": "a magyar kultúráról",
  "Documents & application": "a dokumentumairól",
  "Motivation & future": "a terveiről",
  "Visiting Hungary": "a magyarországi látogatásáról",
  "General": "magáról",
  // Greeting/closing, small talk, interview procedure: no natural "about …" topic.
};

// ---- Speech ---------------------------------------------------------------
const synth = window.speechSynthesis;

function loadVoices() {
  const all = synth ? synth.getVoices() : [];
  huVoices = all.filter((v) => /^hu(-|_|$)/i.test(v.lang));
  ui.voice.innerHTML = "";
  if (huVoices.length === 0) {
    ui.voice.innerHTML = "<option>No Hungarian voice found</option>";
    ui.voice.disabled = true;
    ui.voiceWarning.textContent =
      "⚠ No Hungarian (hu-HU) voice detected. In Microsoft Edge they load automatically when online. " +
      "In Chrome, install a Hungarian language pack in Windows Settings → Time & language → Language.";
  } else {
    ui.voice.disabled = false;
    ui.voiceWarning.textContent = "";
    huVoices.forEach((v, i) => {
      const o = document.createElement("option");
      o.value = i;
      o.textContent = `${v.name}${v.localService ? "" : " (online)"}`;
      ui.voice.appendChild(o);
    });
  }
}

function speak(text) {
  if (!synth || huVoices.length === 0 || !text) return;
  synth.cancel();
  const u = new SpeechSynthesisUtterance(text.replace(/\n/g, ". "));
  u.voice = huVoices[ui.voice.value] || huVoices[0];
  u.lang = u.voice.lang;
  u.rate = parseFloat(ui.rate.value);
  synth.speak(u);
}

// ---- Category + queue -----------------------------------------------------
function buildCategories() {
  const cats = [...new Set(DATA.map((r) => r.category))].sort();
  ui.category.innerHTML = `<option value="__all">All topics (${DATA.length})</option>`;
  cats.forEach((c) => {
    const n = DATA.filter((r) => r.category === c).length;
    const o = document.createElement("option");
    o.value = c;
    o.textContent = `${c} (${n})`;
    ui.category.appendChild(o);
  });
}

// Filtered set = topic match AND question number within [from, to]. The range
// uses the absolute table number so "30–50" means the same regardless of topic.
function applyFilters() {
  let from = parseInt(ui.rangeFrom.value, 10);
  let to = parseInt(ui.rangeTo.value, 10);
  if (!Number.isFinite(from)) from = 1;
  if (!Number.isFinite(to)) to = DATA.length;
  from = Math.max(1, Math.min(from, DATA.length));
  to = Math.max(1, Math.min(to, DATA.length));
  if (from > to) [from, to] = [to, from];
  ui.rangeFrom.value = from;
  ui.rangeTo.value = to;
  ui.rangeLabel.textContent = from === 1 && to === DATA.length ? "(all)" : `(#${from}–${to})`;

  const c = ui.category.value;
  filtered = DATA.filter(
    (r) => (c === "__all" || r.category === c) && r.n >= from && r.n <= to
  );
  queue = [];
}

// Fisher–Yates over the filtered indices, refilled when exhausted (no-repeat).
function nextRow() {
  if (queue.length === 0) {
    queue = filtered.map((_, i) => i);
    for (let i = queue.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [queue[i], queue[j]] = [queue[j], queue[i]];
    }
  }
  return filtered[queue.pop()];
}

// ---- Render ---------------------------------------------------------------
function resetReveals() {
  [ui.enQ, ui.huA, ui.enA].forEach((node) => { node.hidden = true; });
  ui.speakA.hidden = true;
  [...ui.revealButtons.children].forEach((b) => b.classList.remove("active"));
}

function play() {
  if (filtered.length === 0) {
    ui.body.classList.add("hidden");
    ui.empty.classList.remove("hidden");
    ui.empty.innerHTML = "<p>No questions match this topic and range. Widen the range or pick another topic.</p>";
    ui.progress.textContent = "";
    return;
  }
  const row = nextRow();
  if (!row) return;
  let phrasing = row.hu_q;
  const topic = CATEGORY_TOPICS[row.category];
  if (ui.varyOpenings.checked && topic && Math.random() < OPENING_CHANCE) {
    phrasing = `${pickRand(OPENINGS)(topic)} ${phrasing}`;
  }
  current = { row, phrasing };

  ui.empty.classList.add("hidden");
  ui.body.classList.remove("hidden");

  resetReveals();
  ui.qnum.textContent = `#${row.n}`;
  ui.huQ.textContent = phrasing;
  ui.huQ.hidden = ui.hideText.checked;       // interview mode: audio only first
  ui.enQ.textContent = row.en_q;
  ui.huA.textContent = row.hu_a;
  ui.enA.textContent = row.en_a;

  speak(phrasing);
  ui.progress.textContent =
    `${filtered.length - queue.length} / ${filtered.length} in “${ui.category.options[ui.category.selectedIndex].textContent}”`;
}

function toggleReveal(targetId, btn) {
  const node = el(targetId);
  const show = node.hidden;                    // hidden now -> reveal; visible -> hide again
  node.hidden = !show;
  if (btn) btn.classList.toggle("active", show);
  if (targetId === "huA") {
    ui.speakA.hidden = !show;
    if (show) {
      ui.huQ.hidden = false;                   // revealing the answer also shows the question
      speak(current.row.hu_a);
    } else if (synth) {
      synth.cancel();                          // hiding the answer stops it speaking
    }
  }
}

// ---- Wire up --------------------------------------------------------------
ui.play.addEventListener("click", play);
ui.speakQ.addEventListener("click", () => current && speak(current.phrasing));
ui.speakA.addEventListener("click", () => current && speak(current.row.hu_a));

ui.revealButtons.addEventListener("click", (e) => {
  const btn = e.target.closest("button");
  if (!btn || !current) return;
  toggleReveal(btn.dataset.target, btn);
});

ui.rate.addEventListener("input", () => { ui.rateLabel.textContent = `${parseFloat(ui.rate.value).toFixed(2)}×`; });
ui.category.addEventListener("change", applyFilters);
ui.rangeFrom.addEventListener("change", applyFilters);
ui.rangeTo.addEventListener("change", applyFilters);
ui.rangeReset.addEventListener("click", () => {
  ui.rangeFrom.value = 1;
  ui.rangeTo.value = DATA.length;
  applyFilters();
});
ui.hideText.addEventListener("change", () => { if (current) ui.huQ.hidden = ui.hideText.checked; });

// Keyboard: Space/Enter = next, R = replay question.
document.addEventListener("keydown", (e) => {
  if (e.target.tagName === "SELECT" || e.target.tagName === "INPUT") return;
  if (e.code === "Space" || e.code === "Enter") { e.preventDefault(); play(); }
  else if (e.key.toLowerCase() === "r" && current) speak(current.phrasing);
});

if (synth) {
  loadVoices();
  synth.addEventListener("voiceschanged", loadVoices);
}
buildCategories();
ui.rangeFrom.max = DATA.length;
ui.rangeTo.max = DATA.length;
ui.rangeTo.value = DATA.length;
applyFilters();
ui.rateLabel.textContent = `${parseFloat(ui.rate.value).toFixed(2)}×`;
if (DATA.length === 0) ui.empty.innerHTML = "<p>⚠ No data loaded. Run <code>node extract.js</code> first.</p>";
